### ISSUE TITLE
Does it works on flutter web?

### ISSUE THREAD

**Issue by rahulvyas** [bsteps/flutter_photon_rs#2]
Does it works on flutter web?

**Comment by bsteps** [comment]
> Does it works on flutter web?

Currently it doesn't work on flutter web. but it is possible to make it work.

**Comment by rahulvyas** [comment]
what does this mean?
`which compiles to WebAssembly, allowing for safe, blazing-fast image processing both natively and on the web.
`

**Comment by bsteps** [comment]
It's about [`photon`](https://github.com/silvia-odwyer/photon) rust library which can can be complied to webassembly for web use but currently I have not implemented it on flutter side for it to be supported on flutter web.

**Comment by rahulvyas** [comment]
okay, thanks. Any idea on when it will be available? Also, I have a query if you don't mind.
